oauthClient:
  redirectUris:
    - http://localhost:8080/callback
  applicationType: web

directions: |+2
  Okta configuration written to .env.

  Add this file to .gitignore!

  Run this application with:

      mvn quarkus:dev
