oauthClient:
  redirectUris:
    - http://localhost:8080/callback
  applicationType: web

directions: |+2
  Okta configuration written to: src/main/resources/application.properties
  Don't EVER commit src/main/resources/application.properties into source control

  Run this application with:
      mvn quarkus:dev
